#!/usr/bin/env python3
"""Generate every product rule file from catalog/catalog.json and data/inbound-bot-ips.

The generator is offline and deterministic: the same catalog and snapshots always
produce byte-identical output. Run ``python tools/generate.py`` after editing the
catalog or refreshing crawler feeds, and ``python tools/generate.py --check`` in CI
to confirm the committed rule files are current.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import ipaddress
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = Path("catalog") / "catalog.json"
SNAPSHOT_DIR = Path("data") / "inbound-bot-ips"

HEADER = "Generated by tools/generate.py from catalog/catalog.json. Do not edit by hand."
MATCH_TYPES = ("host", "subdomains", "label_suffix", "url_path")
TIERS = ("core", "extended", "candidate")
PROFILES = ("recommended", "full")
FEED_FORMATS = ("google-json", "amazon-html")
DEFENDER_BATCH_LIMIT = 500
CLOUDFLARE_GATEWAY_STANDARD_LIMIT = 1000
CLOUDFLARE_EXPRESSION_LIMIT = 4096
AWS_WAF_REGEX_MAX_LENGTH = 200
AWS_WAF_REGEX_PER_SET = 10

LABEL_RE = re.compile(r"^(?!-)[a-z0-9-]{1,63}(?<!-)$")
TOKEN_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 ._/_-]*$")
BROWSER_PATTERN = re.compile(
    r"^(?:mozilla|applewebkit|chrome|safari|gecko|khtml|linux|windows|macintosh|android|iphone|mobile)(?:/[\d.]+)?$",
    re.IGNORECASE,
)
PATH_RE = re.compile(r"^/[A-Za-z0-9._~/*-]*$")


class CatalogError(ValueError):
    """Raised when the catalog or a snapshot fails validation."""


@dataclass(frozen=True)
class Destination:
    value: str
    match: str
    tier: str
    provider: str
    service: str
    source: str


@dataclass(frozen=True)
class ListName:
    """A DNS name to emit in a list product, after label_suffix expansion."""

    name: str
    subdomains: bool
    destination: Destination


@dataclass(frozen=True)
class UserAgent:
    token: str
    operator: str
    purpose: str
    kind: str
    header: bool
    feed: str | None
    header_patterns: tuple[str, ...] = ()


@dataclass(frozen=True)
class Feed:
    feed_id: str
    operator: str
    tokens: tuple[str, ...]
    url: str
    fmt: str
    snapshot: str
    aggregate: bool


# --------------------------------------------------------------------------- #
# Catalog loading and validation
# --------------------------------------------------------------------------- #


def valid_hostname(name: str) -> bool:
    if not name or len(name) > 253 or name.endswith("."):
        return False
    labels = name.split(".")
    return len(labels) >= 2 and all(LABEL_RE.match(label) for label in labels)


def load_catalog(root: Path = ROOT) -> dict:
    with open(root / CATALOG_PATH, encoding="utf-8") as handle:
        catalog = json.load(handle)
    validate_catalog(catalog)
    return catalog


def validate_catalog(catalog: dict) -> None:
    if catalog.get("schema_version") != 1:
        raise CatalogError("catalog schema_version must be 1")
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", catalog.get("reviewed", "")):
        raise CatalogError("catalog reviewed must be an ISO date")

    egress = catalog["egress"]
    for profile in PROFILES:
        tiers = egress["profiles"].get(profile)
        if not tiers or any(tier not in TIERS for tier in tiers):
            raise CatalogError(f"profile {profile} must list known tiers")

    never_block = set(egress["never_block"])
    seen: set[str] = set()
    for entry in egress["entries"]:
        value, match, tier = entry["value"], entry["match"], entry["tier"]
        if match not in MATCH_TYPES:
            raise CatalogError(f"{value}: unknown match type {match}")
        if tier not in TIERS:
            raise CatalogError(f"{value}: unknown tier {tier}")
        for field in ("provider", "service", "source"):
            if not entry.get(field):
                raise CatalogError(f"{value}: missing {field}")
        if value in seen:
            raise CatalogError(f"duplicate egress entry {value}")
        seen.add(value)
        if match in ("host", "subdomains"):
            if not valid_hostname(value):
                raise CatalogError(f"{value}: not a valid hostname")
            if value in never_block:
                raise CatalogError(f"{value}: listed in never_block")
        elif match == "label_suffix":
            if not value.startswith("-") or not valid_hostname("x" + value):
                raise CatalogError(f"{value}: label_suffix must start with '-' and form a hostname")
            if entry.get("enumerate") != "vertex_regions":
                raise CatalogError(f"{value}: label_suffix requires enumerate=vertex_regions")
        elif match == "url_path":
            host, _, path = value.partition("/")
            if not valid_hostname(host) or not PATH_RE.match("/" + path):
                raise CatalogError(f"{value}: url_path must be host/path")

    bedrock = egress["bedrock"]
    if bedrock["tier"] not in TIERS:
        raise CatalogError("bedrock tier unknown")
    for service in bedrock["services"]:
        for host in service["hosts"]:
            if not valid_hostname(host):
                raise CatalogError(f"bedrock host {host} is not a valid hostname")
            if host in seen:
                raise CatalogError(f"duplicate egress entry {host}")
            seen.add(host)

    for region in egress["vertex_regions"]["regions"]:
        if not LABEL_RE.match(region):
            raise CatalogError(f"vertex region {region} is not a DNS label")

    for address in egress["observed_inference_addresses"]["addresses"]:
        ipaddress.ip_address(address)
    for prefix in egress["observed_inference_addresses"]["shared_prefixes"]:
        ipaddress.ip_network(prefix, strict=True)

    inbound = catalog["inbound"]
    feed_ids: set[str] = set()
    for feed in inbound["feeds"]:
        if feed["format"] not in FEED_FORMATS:
            raise CatalogError(f"feed {feed['id']}: unknown format {feed['format']}")
        if feed["id"] in feed_ids:
            raise CatalogError(f"duplicate feed {feed['id']}")
        if not feed["url"].startswith("https://"):
            raise CatalogError(f"feed {feed['id']}: url must be https")
        feed_ids.add(feed["id"])

    tokens: set[str] = set()
    for agent in inbound["user_agents"]:
        token = agent["token"]
        if not TOKEN_RE.match(token) or " " in token:
            raise CatalogError(f"user agent token {token!r} is not a single product token")
        if token.lower() in tokens:
            raise CatalogError(f"duplicate user agent token {token}")
        tokens.add(token.lower())
        if agent["feed"] is not None and agent["feed"] not in feed_ids:
            raise CatalogError(f"user agent {token}: unknown feed {agent['feed']}")
        if agent["purpose"] not in ("training", "search", "user", "ads"):
            raise CatalogError(f"user agent {token}: unknown purpose {agent['purpose']}")
        if agent["kind"] not in ("documented", "common"):
            raise CatalogError(f"user agent {token}: unknown kind {agent['kind']}")
        patterns = agent.get("header_patterns", [])
        if not isinstance(patterns, list):
            raise CatalogError(f"user agent {token}: header_patterns must be a list")
        if patterns and not agent["header"]:
            raise CatalogError(f"user agent {token}: header_patterns require header matching")
        for pattern in patterns:
            validate_header_pattern(token, pattern)

    for token in inbound["community_robots_tokens"]["tokens"]:
        if not TOKEN_RE.match(token):
            raise CatalogError(f"community token {token!r} contains unsupported characters")

    sid_base = catalog["suricata"]["sid_base"]
    bases = sorted(sid_base.values())
    for low, high in zip(bases, bases[1:]):
        if high - low < 100000:
            raise CatalogError("suricata sid_base ranges must be at least 100000 apart")

    validate_provider_network(catalog, "anthropic_network", "AP-2440")
    validate_provider_network(catalog, "openai_network", "OOL-15")
    validate_provider_network(catalog, "xai_network", "XAI")


def validate_header_pattern(token: str, pattern: str) -> None:
    if not isinstance(pattern, str) or len(pattern) < 4:
        raise CatalogError(f"user agent {token}: header pattern {pattern!r} is shorter than 4 characters")
    if any(character in pattern for character in '#\r\n";'):
        raise CatalogError(f"user agent {token}: header pattern {pattern!r} contains a character the rules cannot quote")
    if BROWSER_PATTERN.match(pattern):
        raise CatalogError(f"user agent {token}: header pattern {pattern!r} is a browser token")


def validate_provider_network(catalog: dict, key: str, org_handle: str) -> None:
    """Reject an inventory entry that would emit an excluded allocation."""
    network = catalog[key]
    if network.get("org_handle") != org_handle:
        raise CatalogError(f"{key} org_handle must be {org_handle}")
    excluded = [ipaddress.ip_network(value, strict=True) for value in network["do_not_emit"]]
    emitted: list[Network] = []
    for item in network["prefixes"]:
        if not item.get("source", "").startswith("https://"):
            raise CatalogError(f"{item.get('prefix')}: {key} source must be https")
        prefix = ipaddress.ip_network(item["prefix"], strict=True)
        if not item["emit"]:
            continue
        emitted.append(prefix)
        for banned in excluded:
            if prefix.version == banned.version and (prefix == banned or prefix.supernet_of(banned)):
                raise CatalogError(f"{prefix} covers excluded prefix {banned}")
    if not emitted:
        raise CatalogError(f"{key} has no emitted prefixes")


def destinations(catalog: dict, profile: str) -> list[Destination]:
    egress = catalog["egress"]
    tiers = egress["profiles"][profile]
    result: list[Destination] = []
    bedrock = egress["bedrock"]
    bedrock_destinations = [
        Destination(host, "host", bedrock["tier"], bedrock["provider"], service["service"], service["source"])
        for service in bedrock["services"]
        for host in service["hosts"]
    ]
    for tier in TIERS:
        if tier not in tiers:
            continue
        for entry in egress["entries"]:
            if entry["tier"] == tier:
                result.append(
                    Destination(
                        entry["value"], entry["match"], tier, entry["provider"], entry["service"], entry["source"]
                    )
                )
        if bedrock["tier"] == tier:
            result.extend(bedrock_destinations)
    return result


def vertex_hosts(catalog: dict, suffix: str) -> list[str]:
    return [region + suffix for region in catalog["egress"]["vertex_regions"]["regions"]]


def list_names(catalog: dict, dests: list[Destination]) -> list[ListName]:
    """Flatten destinations into DNS names; label_suffix entries become enumerated hosts."""
    names: list[ListName] = []
    seen: set[str] = set()
    for dest in dests:
        if dest.match == "host":
            candidates = [(dest.value, False)]
        elif dest.match == "subdomains":
            candidates = [(dest.value, True)]
        elif dest.match == "label_suffix":
            candidates = [(host, False) for host in vertex_hosts(catalog, dest.value)]
        else:
            continue
        for name, subdomains in candidates:
            if name not in seen:
                seen.add(name)
                names.append(ListName(name, subdomains, dest))
    return names


def covered_by(name: str, parents: set[str]) -> bool:
    """True when a proper parent domain of name is present in parents."""
    labels = name.split(".")
    return any(".".join(labels[index:]) in parents for index in range(1, len(labels) - 1))


def suffix_names(names: list[ListName]) -> list[ListName]:
    """Names for products whose entries always include subdomains, with redundant children removed."""
    all_names = {item.name for item in names}
    return [item for item in names if not covered_by(item.name, all_names)]


def pattern_destinations(dests: list[Destination], match: str) -> list[Destination]:
    return [dest for dest in dests if dest.match == match]


def label(dest: Destination) -> str:
    if dest.service.lower().startswith(dest.provider.lower()):
        return dest.service
    return f"{dest.provider} {dest.service}"


# --------------------------------------------------------------------------- #
# Regular expression helpers
# --------------------------------------------------------------------------- #

REGEX_SPECIALS = set(".^$*+?()[]{}|\\/")


def rx_escape(text: str, escape_slash: bool = False) -> str:
    out = []
    for char in text:
        if char in REGEX_SPECIALS and (char != "/" or escape_slash):
            out.append("\\" + char)
        else:
            out.append(char)
    return "".join(out)


def label_suffix_regex(suffix: str, escape_slash: bool = False) -> str:
    return "(^|\\.)[a-z0-9-]+" + rx_escape(suffix, escape_slash) + "$"


def url_path_parts(value: str) -> tuple[str, str]:
    host, _, path = value.partition("/")
    return host, "/" + path


def url_path_regex(value: str, escape_slash: bool = False) -> str:
    """Regex for the URL path only; '*' matches one path segment."""
    _, path = url_path_parts(value)
    segment = "[^\\/]+" if escape_slash else "[^/]+"
    return "^" + segment.join(rx_escape(part, escape_slash) for part in path.split("*"))


# --------------------------------------------------------------------------- #
# Crawler address feeds
# --------------------------------------------------------------------------- #

Network = ipaddress.IPv4Network | ipaddress.IPv6Network


def feeds(catalog: dict) -> list[Feed]:
    return [
        Feed(
            item["id"], item["operator"], tuple(item["tokens"]), item["url"], item["format"],
            item["snapshot"], bool(item["aggregate"]),
        )
        for item in catalog["inbound"]["feeds"]
    ]


def parse_network(text: str) -> Network:
    text = text.strip()
    try:
        return ipaddress.ip_network(text, strict=True)
    except ValueError:
        network = ipaddress.ip_network(text, strict=False)
        raise CatalogError(f"{text} has host bits set; expected {network}") from None


def parse_google_json(payload: str) -> list[Network]:
    document = json.loads(payload)
    prefixes = document.get("prefixes")
    if not isinstance(prefixes, list):
        raise CatalogError("feed document has no prefixes array")
    networks: list[Network] = []
    for item in prefixes:
        value = item.get("ipv4Prefix") or item.get("ipv6Prefix")
        if not value:
            raise CatalogError(f"feed prefix entry without ipv4Prefix or ipv6Prefix: {item}")
        networks.append(parse_network(value))
    return networks


AMAZON_KEY_RE = re.compile(r'"(?:ipv4Prefix|ipv6Prefix|ip_prefix|ipv6_prefix)"\s*:\s*"([^"]+)"')


def parse_amazon_html(payload: str) -> list[Network]:
    """Extract prefixes from the JSON embedded in Amazon's crawler address pages."""
    values = AMAZON_KEY_RE.findall(payload)
    if not values:
        raise CatalogError("no ipv4Prefix, ipv6Prefix, ip_prefix, or ipv6_prefix keys found in page")
    return [ipaddress.ip_network(value.strip(), strict=False) for value in values]


def parse_prefix_lines(payload: str) -> list[Network]:
    networks: list[Network] = []
    for line in payload.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            networks.append(parse_network(line))
    return networks


def load_feed_snapshot(root: Path, feed: Feed) -> list[Network]:
    path = root / SNAPSHOT_DIR / feed.snapshot
    if not path.is_file():
        raise CatalogError(f"missing snapshot {path.relative_to(root)} for feed {feed.feed_id}; run tools/refresh_feeds.py")
    payload = path.read_text(encoding="utf-8")
    if feed.snapshot.endswith(".json"):
        networks = parse_google_json(payload)
    else:
        networks = parse_prefix_lines(payload)
    if not networks:
        raise CatalogError(f"snapshot {feed.snapshot} contains no prefixes")
    return networks


def collapse(networks: list[Network]) -> tuple[list[ipaddress.IPv4Network], list[ipaddress.IPv6Network]]:
    v4 = [net for net in networks if net.version == 4]
    v6 = [net for net in networks if net.version == 6]
    return list(ipaddress.collapse_addresses(v4)), list(ipaddress.collapse_addresses(v6))


def guard_networks(catalog: dict, networks: list[Network], context: str) -> list[Network]:
    """Drop any prefix that would cover a shared inference front end."""
    guard = catalog["egress"]["observed_inference_addresses"]
    addresses = [ipaddress.ip_address(value) for value in guard["addresses"]]
    shared = [ipaddress.ip_network(value) for value in guard["shared_prefixes"]]
    kept: list[Network] = []
    for net in networks:
        hit = next((str(addr) for addr in addresses if addr.version == net.version and addr in net), None)
        if hit is None:
            hit = next(
                (str(pre) for pre in shared if pre.version == net.version and (net == pre or net.supernet_of(pre))),
                None,
            )
        if hit is not None:
            print(f"warning: {context}: dropped {net} because it covers shared inference address space {hit}", file=sys.stderr)
            continue
        kept.append(net)
    return kept


@dataclass
class FeedData:
    feed: Feed
    ipv4: list[ipaddress.IPv4Network]
    ipv6: list[ipaddress.IPv6Network]


def load_feed_data(root: Path, catalog: dict) -> list[FeedData]:
    result = []
    for feed in feeds(catalog):
        networks = guard_networks(catalog, load_feed_snapshot(root, feed), feed.feed_id)
        ipv4, ipv6 = collapse(networks)
        result.append(FeedData(feed, ipv4, ipv6))
    return result


def aggregate_networks(feed_data: list[FeedData]) -> tuple[list[ipaddress.IPv4Network], list[ipaddress.IPv6Network]]:
    networks: list[Network] = []
    for item in feed_data:
        if item.feed.aggregate:
            networks.extend(item.ipv4)
            networks.extend(item.ipv6)
    return collapse(networks)


# --------------------------------------------------------------------------- #
# Output helpers
# --------------------------------------------------------------------------- #


def provider_network_file(catalog: dict, key: str) -> str:
    """Registry-confirmed prefixes for one provider, collapsed, with exclusions omitted."""
    network = catalog[key]
    emitted = [ipaddress.ip_network(item["prefix"], strict=True) for item in network["prefixes"] if item["emit"]]
    ipv4, ipv6 = collapse(emitted)
    return commented("#", [str(net) for net in ipv4 + ipv6], network["notes"])


def lines(items: list[str]) -> str:
    return "\n".join(items) + "\n" if items else ""


def commented(prefix: str, body: list[str], extra: list[str] | None = None) -> str:
    head = [f"{prefix} {HEADER}"]
    for note in extra or []:
        head.append(f"{prefix} {note}" if note else prefix)
    return lines(head + body)


def profile_suffix(profile: str) -> str:
    return "" if profile == "recommended" else "-full"


def csv_text(rows: list[list[str]]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerows(rows)
    return buffer.getvalue()


# --------------------------------------------------------------------------- #
# Egress products
# --------------------------------------------------------------------------- #


def palo_alto_url_edl(catalog: dict, dests: list[Destination]) -> str:
    entries = []
    for item in list_names(catalog, dests):
        entries.append(("*." if item.subdomains else "") + item.name + "/")
    for dest in pattern_destinations(dests, "url_path"):
        entries.append(dest.value)
    return lines(entries)


def zscaler_urls(catalog: dict, dests: list[Destination]) -> str:
    return lines([("." if item.subdomains else "") + item.name for item in list_names(catalog, dests)])


def netskope_urls(catalog: dict, dests: list[Destination], profile: str) -> str:
    body = [("*." if item.subdomains else "") + item.name for item in list_names(catalog, dests)]
    return commented("#", body, [f"Netskope exact/wildcard URL list, profile: {profile}."])


def netskope_regex(dests: list[Destination]) -> str:
    body = []
    for dest in pattern_destinations(dests, "label_suffix"):
        body.append("^[a-z0-9-]+" + rx_escape(dest.value) + "(:[0-9]+)?(/|$)")
    for dest in pattern_destinations(dests, "url_path"):
        host, _ = url_path_parts(dest.value)
        body.append("^" + rx_escape(host) + "(:[0-9]+)?" + url_path_regex(dest.value)[1:])
    return commented("#", body, ["Netskope regex URL list (PCRE, no scheme)."])


def cloudflare_gateway_csv(catalog: dict, dests: list[Destination]) -> str:
    rows = [["value", "description"]]
    for item in suffix_names(list_names(catalog, dests)):
        rows.append([item.name, label(item.destination)])
    return csv_text(rows)


def umbrella_destinations(catalog: dict, dests: list[Destination]) -> str:
    return lines([item.name for item in suffix_names(list_names(catalog, dests))])


def squid_domains(catalog: dict, dests: list[Destination], profile: str) -> str:
    body = ["." + item.name for item in suffix_names(list_names(catalog, dests))]
    return commented("#", body, [f"Squid dstdomain / ssl::server_name list, profile: {profile}."])


def squid_domain_regex(dests: list[Destination]) -> str:
    body = [label_suffix_regex(dest.value) for dest in pattern_destinations(dests, "label_suffix")]
    return commented("#", body, ["Squid dstdom_regex / ssl::server_name_regex list. Use with -i."])


def squid_url_regex(dests: list[Destination]) -> str:
    body = []
    for dest in pattern_destinations(dests, "url_path"):
        host, _ = url_path_parts(dest.value)
        body.append("^https?://" + rx_escape(host) + "(:[0-9]+)?" + url_path_regex(dest.value)[1:])
    return commented("#", body, ["Squid url_regex list. Matches only requests Squid can see in full (HTTP or bumped HTTPS)."])


def tmsh_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def f5_datagroups(catalog: dict, dests: list[Destination], profile: str) -> str:
    names = list_names(catalog, dests)
    exact = [item for item in names if not item.subdomains]
    suffixes = [item for item in names if item.subdomains]
    patterns = pattern_destinations(dests, "label_suffix")
    paths = pattern_destinations(dests, "url_path")

    out = [f"# {HEADER}", f"# Profile: {profile}. Load with: tmsh load sys config merge file <path-to-this-file>", ""]

    def group(name: str, records: list[tuple[str, str]]) -> None:
        out.append(f"ltm data-group internal {name} {{")
        out.append("    records {")
        for key, data in records:
            out.append(f"        {tmsh_quote(key)} {{")
            out.append(f"            data {tmsh_quote(data)}")
            out.append("        }")
        out.append("    }")
        out.append("    type string")
        out.append("}")

    group("ai_inference_hosts", [(item.name, label(item.destination)) for item in exact])
    group("ai_inference_suffixes", [("." + item.name, label(item.destination)) for item in suffixes])
    group("ai_inference_label_suffixes", [(dest.value, label(dest)) for dest in patterns])
    group("ai_inference_url_paths", [(dest.value, label(dest)) for dest in paths])
    return lines(out)


def rpz_zone(catalog: dict, dests: list[Destination], profile: str) -> str:
    serial = catalog["reviewed"].replace("-", "") + "01"
    out = [
        f"; {HEADER}",
        f"; Response policy zone, profile: {profile}. CNAME . returns NXDOMAIN to the client.",
        "$TTL 300",
        f"@ IN SOA localhost. hostmaster.localhost. ( {serial} 3600 600 86400 300 )",
        "@ IN NS localhost.",
    ]
    for item in list_names(catalog, dests):
        out.append(f"; {label(item.destination)}")
        if not item.subdomains:
            out.append(f"{item.name} CNAME .")
        out.append(f"*.{item.name} CNAME .")
    return lines(out)


def pihole_adlist(catalog: dict, dests: list[Destination], profile: str) -> str:
    body = ["||" + item.name + "^" for item in suffix_names(list_names(catalog, dests))]
    head = [f"! {HEADER}", f"! Pi-hole v6 ABP-style adlist, profile: {profile}. Each entry blocks the domain and its subdomains."]
    return lines(head + body)


def pihole_domains(catalog: dict, dests: list[Destination], profile: str) -> str:
    body = [item.name for item in suffix_names(list_names(catalog, dests))]
    return commented("#", body, [f"Domains for 'pihole --wild', profile: {profile}. Read by install.sh."])


def pihole_regex(dests: list[Destination]) -> str:
    body = [label_suffix_regex(dest.value) for dest in pattern_destinations(dests, "label_suffix")]
    return commented("#", body, ["POSIX ERE filters for 'pihole --regex'. Read by install.sh."])


DEFENDER_COLUMNS = [
    "indicatorType", "indicatorValue", "action", "title", "description", "expirationTime",
    "severity", "recommendedActions", "rbacGroups", "category", "mitretechniques", "GenerateAlert",
]


def defender_rows(catalog: dict, dests: list[Destination]) -> list[list[str]]:
    rows = []
    for item in list_names(catalog, dests):
        if item.subdomains:
            continue
        dest = item.destination
        rows.append([
            "DomainName",
            item.name,
            "Block",
            f"AI inference API: {dest.provider}"[:100],
            f"Hosted AI inference endpoint ({dest.service}). Catalog tier: {dest.tier}. Source: {dest.source}",
            "",
            "Medium",
            "Confirm whether the process is an approved AI integration. If it is not, investigate the device for unauthorized AI tooling.",
            "",
            "",
            "",
            "True",
        ])
    return rows


def defender_files(catalog: dict, dests: list[Destination], profile: str) -> dict[str, str]:
    rows = defender_rows(catalog, dests)
    base = f"rules/microsoft-defender/ai-inference-indicators{profile_suffix(profile)}"
    chunks = [rows[i:i + DEFENDER_BATCH_LIMIT] for i in range(0, len(rows), DEFENDER_BATCH_LIMIT)]
    files = {}
    for index, chunk in enumerate(chunks, start=1):
        name = f"{base}.csv" if len(chunks) == 1 else f"{base}-part{index}.csv"
        files[name] = csv_text([DEFENDER_COLUMNS] + chunk)
    return files


# --------------------------------------------------------------------------- #
# Suricata
# --------------------------------------------------------------------------- #


def suricata_msg(text: str) -> str:
    return re.sub(r'[;"\\]', " ", text)


SID_SPACE = 99999


def suricata_sid_map(catalog: dict) -> dict[tuple[str, str], int]:
    """SID offsets derived from a hash of each entry, so adding entries never renumbers existing rules.

    Collisions are resolved by linear probing in sorted key order, which keeps the result
    independent of catalog ordering.
    """
    return stable_offsets({(dest.match, dest.value) for dest in destinations(catalog, "full")})


def stable_offsets(keys: set[tuple[str, str]]) -> dict[tuple[str, str], int]:
    offsets: dict[tuple[str, str], int] = {}
    used: set[int] = set()
    for key in sorted(keys):
        digest = hashlib.sha256(f"{key[0]}:{key[1]}".encode("utf-8")).digest()
        offset = int.from_bytes(digest[:8], "big") % SID_SPACE + 1
        while offset in used:
            offset = offset % SID_SPACE + 1
        used.add(offset)
        offsets[key] = offset
    return offsets


def suricata_host_rule(proto: str, buffer: str, direction: str, flow: str | None, sid: int, rev: int,
                       msg: str, content: str, pcre: str, tier: str) -> str:
    parts = [f'msg:"{suricata_msg(msg)}"']
    if flow:
        parts.append(f"flow:{flow}")
    parts.append(f"{buffer}")
    parts.append(f'content:"{content}"')
    if buffer != "http.host":
        parts.append("nocase")
    parts.append("fast_pattern")
    parts.append(f'pcre:"/{pcre}/i"')
    parts.append("classtype:policy-violation")
    parts.append(f"metadata:tier {tier}")
    parts.append(f"sid:{sid}")
    parts.append(f"rev:{rev}")
    return f"alert {proto} {direction} (" + "; ".join(parts) + ";)"


def suricata_match(dest: Destination) -> tuple[str, str]:
    """Return (content, pcre) for a host, subdomains, or label_suffix destination."""
    if dest.match == "host":
        return dest.value, "(?:^|\\.)" + rx_escape(dest.value, escape_slash=True) + "$"
    if dest.match == "subdomains":
        return "." + dest.value, "\\." + rx_escape(dest.value, escape_slash=True) + "$"
    if dest.match == "label_suffix":
        return dest.value, "[a-z0-9-]" + rx_escape(dest.value, escape_slash=True) + "$"
    raise CatalogError(f"no host match for {dest.match}")


def suricata_egress_rules(catalog: dict, dests: list[Destination], profile: str) -> str:
    sid_base = catalog["suricata"]["sid_base"]
    rev = catalog["suricata"]["rev"]
    offsets = suricata_sid_map(catalog)
    out = [
        f"# {HEADER}",
        f"# Suricata 7+ egress rules for hosted AI inference, profile: {profile}.",
        "# Rules alert by default. Convert to drop with suricata-update drop.conf (re:AI-INFERENCE) in IPS mode.",
        "",
        "# TLS SNI",
    ]
    host_dests = [dest for dest in dests if dest.match in ("host", "subdomains", "label_suffix")]
    for dest in host_dests:
        content, pcre = suricata_match(dest)
        out.append(suricata_host_rule(
            "tls", "tls.sni", "$HOME_NET any -> $EXTERNAL_NET any", "established,to_server",
            sid_base["tls_sni"] + offsets[(dest.match, dest.value)], rev,
            f"AI-INFERENCE TLS SNI {dest.provider} {dest.value}", content, pcre, dest.tier,
        ))
    out.append("")
    out.append("# DNS query")
    for dest in host_dests:
        content, pcre = suricata_match(dest)
        out.append(suricata_host_rule(
            "dns", "dns.query", "$HOME_NET any -> any any", None,
            sid_base["dns_query"] + offsets[(dest.match, dest.value)], rev,
            f"AI-INFERENCE DNS query {dest.provider} {dest.value}", content, pcre, dest.tier,
        ))
    out.append("")
    out.append("# HTTP Host (plaintext HTTP or decrypted traffic)")
    for dest in host_dests:
        content, pcre = suricata_match(dest)
        out.append(suricata_host_rule(
            "http", "http.host", "$HOME_NET any -> $EXTERNAL_NET any", "established,to_server",
            sid_base["http_host"] + offsets[(dest.match, dest.value)], rev,
            f"AI-INFERENCE HTTP Host {dest.provider} {dest.value}", content, pcre, dest.tier,
        ))
    for dest in pattern_destinations(dests, "url_path"):
        host, _ = url_path_parts(dest.value)
        sid = sid_base["http_host"] + offsets[(dest.match, dest.value)]
        path_pcre = url_path_regex(dest.value, escape_slash=True)
        parts = [
            f'msg:"{suricata_msg("AI-INFERENCE HTTP path " + dest.provider + " " + dest.value)}"',
            "flow:established,to_server",
            "http.host",
            f'content:"{host}"',
            f'pcre:"/^{rx_escape(host, escape_slash=True)}$/i"',
            "http.uri",
            f'pcre:"/{path_pcre}/"',
            "classtype:policy-violation",
            f"metadata:tier {dest.tier}",
            f"sid:{sid}",
            f"rev:{rev}",
        ]
        out.append("alert http $HOME_NET any -> $EXTERNAL_NET any (" + "; ".join(parts) + ";)")
    return lines(out)


def suricata_crawler_rules(catalog: dict) -> str:
    sid_base = catalog["suricata"]["sid_base"]["http_user_agent"]
    rev = catalog["suricata"]["rev"]
    out = [
        f"# {HEADER}",
        "# Suricata 7+ inbound rules for AI crawler user-agent tokens sent to your published services.",
        "# User-agent strings are self-asserted; pair these rules with the address feeds in rules/ip-feeds.",
        "",
    ]
    agents = [agent for agent in user_agents(catalog) if agent.header]
    pattern_owner: dict[str, UserAgent] = {}
    for agent in agents:
        for pattern in header_match_patterns(agent):
            pattern_owner.setdefault(pattern.lower(), agent)
    offsets = stable_offsets({("user_agent", pattern) for pattern in pattern_owner})
    for pattern in sorted(pattern_owner):
        agent = pattern_owner[pattern]
        index = offsets[("user_agent", pattern)]
        parts = [
            f'msg:"{suricata_msg(f"AI-CRAWLER User-Agent {agent.token} ({agent.operator})")}"',
            "flow:established,to_server",
            "http.user_agent",
            f'content:"{pattern}"',
            "nocase",
            "classtype:policy-violation",
            f"metadata:purpose {agent.purpose}",
            f"sid:{sid_base + index}",
            f"rev:{rev}",
        ]
        out.append("alert http $EXTERNAL_NET any -> $HOME_NET any (" + "; ".join(parts) + ";)")
    return lines(out)


# --------------------------------------------------------------------------- #
# F5 iRules (static logic, data comes from the data groups)
# --------------------------------------------------------------------------- #

F5_PROC = """proc ai_inference_host_blocked { host } {
    set host [string trimright [string tolower $host] "."]
    if { $host eq "" } { return 0 }
    if { [class match -- $host equals ai_inference_hosts] } { return 1 }
    if { [class match -- $host ends_with ai_inference_suffixes] } { return 1 }
    set first_label [lindex [split $host "."] 0]
    set remainder [string range $host [string length $first_label] end]
    foreach suffix [class names ai_inference_label_suffixes] {
        set suffix_domain [string range $suffix [string first "." $suffix] end]
        set suffix_label [string range $suffix 0 [expr {[string first "." $suffix] - 1}]]
        if { $remainder eq $suffix_domain && [string length $first_label] > [string length $suffix_label]
             && [string range $first_label end-[expr {[string length $suffix_label] - 1}] end] eq $suffix_label } {
            return 1
        }
    }
    return 0
}

proc ai_inference_path_blocked { host path } {
    set host [string trimright [string tolower $host] "."]
    foreach entry [class names ai_inference_url_paths] {
        set slash [string first "/" $entry]
        if { $host eq [string range $entry 0 [expr {$slash - 1}]] } {
            set pattern "[string range $entry $slash end]*"
            if { [string match $pattern $path] } { return 1 }
        }
    }
    return 0
}
"""

F5_IRULE = f"""# {HEADER}
# AI inference egress iRule for BIG-IP forward proxy and SSL Orchestrator deployments.
# Requires the data groups from ai-inference-datagroups.tmsh. Attach to a virtual server with an
# HTTP profile (explicit proxy) and, for TLS inspection, a client SSL profile.

{F5_PROC}
when CLIENTSSL_CLIENTHELLO priority 100 {{
    if {{ [SSL::extensions exists -type 0] }} {{
        binary scan [SSL::extensions -type 0] {{@9A*}} ai_sni
        if {{ [call ai_inference_host_blocked $ai_sni] }} {{
            log local0.notice "AI inference TLS blocked: client=[IP::client_addr] sni=$ai_sni"
            reject
            event disable all
        }}
    }}
}}

when HTTP_REQUEST priority 100 {{
    if {{ [HTTP::method] eq "CONNECT" }} {{
        set ai_host [lindex [split [HTTP::uri] ":"] 0]
    }} else {{
        set ai_host [lindex [split [HTTP::host] ":"] 0]
    }}
    if {{ [call ai_inference_host_blocked $ai_host] }} {{
        log local0.notice "AI inference HTTP blocked: client=[IP::client_addr] host=$ai_host"
        HTTP::respond 403 content "Access to hosted AI inference services is blocked by policy." "Content-Type" "text/plain" "Connection" "close"
        event disable all
        return
    }}
    if {{ [HTTP::method] ne "CONNECT" && [call ai_inference_path_blocked $ai_host [HTTP::path]] }} {{
        log local0.notice "AI inference path blocked: client=[IP::client_addr] host=$ai_host path=[HTTP::path]"
        HTTP::respond 403 content "Access to hosted AI inference services is blocked by policy." "Content-Type" "text/plain" "Connection" "close"
        event disable all
    }}
}}
"""

F5_PASSTHROUGH_IRULE = f"""# {HEADER}
# AI inference egress iRule for BIG-IP virtual servers that forward TLS without a client SSL profile.
# Parses the TLS ClientHello server_name extension from the first client record and rejects matches.
# Requires the data groups from ai-inference-datagroups.tmsh. Attach to a standard TCP virtual server.

{F5_PROC}
when CLIENT_ACCEPTED priority 100 {{
    set ai_collected 0
    TCP::collect
}}

when CLIENT_DATA priority 100 {{
    set ai_payload [TCP::payload]
    set ai_length [string length $ai_payload]
    if {{ $ai_length < 5 }} {{
        if {{ $ai_collected == 0 }} {{ set ai_collected 1; TCP::collect 5; return }}
        TCP::release
        return
    }}
    binary scan $ai_payload cSS ai_record_type ai_record_version ai_record_length
    set ai_record_type [expr {{$ai_record_type & 0xff}}]
    set ai_record_length [expr {{$ai_record_length & 0xffff}}]
    if {{ $ai_record_type != 22 }} {{
        TCP::release
        return
    }}
    set ai_needed [expr {{5 + $ai_record_length}}]
    if {{ $ai_length < $ai_needed && $ai_collected < 2 }} {{
        set ai_collected 2
        TCP::collect $ai_needed
        return
    }}
    set ai_sni ""
    binary scan $ai_payload @5c ai_handshake_type
    if {{ [expr {{$ai_handshake_type & 0xff}}] == 1 }} {{
        # Skip record header (5), handshake header (4), client version (2), random (32).
        set offset 43
        binary scan $ai_payload @${{offset}}c ai_len
        set offset [expr {{$offset + 1 + ($ai_len & 0xff)}}]
        binary scan $ai_payload @${{offset}}S ai_len
        set offset [expr {{$offset + 2 + ($ai_len & 0xffff)}}]
        binary scan $ai_payload @${{offset}}c ai_len
        set offset [expr {{$offset + 1 + ($ai_len & 0xff)}}]
        if {{ [binary scan $ai_payload @${{offset}}S ai_ext_total] == 1 }} {{
            set offset [expr {{$offset + 2}}]
            set ai_ext_end [expr {{$offset + ($ai_ext_total & 0xffff)}}]
            if {{ $ai_ext_end > $ai_length }} {{ set ai_ext_end $ai_length }}
            while {{ $offset + 4 <= $ai_ext_end }} {{
                binary scan $ai_payload @${{offset}}SS ai_ext_type ai_ext_len
                set ai_ext_type [expr {{$ai_ext_type & 0xffff}}]
                set ai_ext_len [expr {{$ai_ext_len & 0xffff}}]
                if {{ $ai_ext_type == 0 }} {{
                    # server_name_list length (2), name_type (1), host_name length (2), host_name.
                    if {{ [binary scan $ai_payload @[expr {{$offset + 7}}]S ai_name_len] == 1 }} {{
                        set ai_name_len [expr {{$ai_name_len & 0xffff}}]
                        binary scan $ai_payload @[expr {{$offset + 9}}]a${{ai_name_len}} ai_sni
                    }}
                    break
                }}
                set offset [expr {{$offset + 4 + $ai_ext_len}}]
            }}
        }}
    }}
    if {{ $ai_sni ne "" && [call ai_inference_host_blocked $ai_sni] }} {{
        log local0.notice "AI inference TLS blocked: client=[IP::client_addr] sni=$ai_sni"
        reject
        return
    }}
    TCP::release
}}
"""


# --------------------------------------------------------------------------- #
# Inbound products
# --------------------------------------------------------------------------- #


def plugin_catalog(catalog: dict) -> str:
    """Self-contained data file for the WordPress, DirectAdmin, and WHM plugins."""
    documented = []
    seen: set[str] = set()
    for agent in user_agents(catalog):
        documented.append(
            {
                "token": agent.token,
                "operator": agent.operator,
                "purpose": agent.purpose,
                "header": agent.header,
                "header_patterns": list(agent.header_patterns),
                "profile": "recommended",
            }
        )
        seen.add(agent.token.lower())
    community = []
    for token in catalog["inbound"]["community_robots_tokens"]["tokens"]:
        if token.lower() in seen:
            continue
        seen.add(token.lower())
        community.append(
            {
                "token": token,
                "operator": "",
                "purpose": "community",
                "header": False,
                "header_patterns": [],
                "profile": "full",
            }
        )

    def groups(profile: str) -> list[dict]:
        merged: dict[tuple, dict] = {}
        order: list[tuple] = []
        recommended_tiers = set(catalog["egress"]["profiles"]["recommended"])
        for dest in destinations(catalog, profile):
            key = (dest.provider, dest.service, dest.match)
            if key not in merged:
                merged[key] = {
                    "id": f"{dest.provider}:{dest.service}:{dest.match}",
                    "provider": dest.provider,
                    "service": dest.service,
                    "match": dest.match,
                    "values": [],
                    "profile": "recommended" if dest.tier in recommended_tiers else "full",
                }
                order.append(key)
            if dest.value not in merged[key]["values"]:
                merged[key]["values"].append(dest.value)
        return [merged[key] for key in order]

    recommended_ids = {item["id"] for item in groups("recommended")}
    inference = groups("recommended")
    for item in groups("full"):
        if item["id"] not in recommended_ids:
            inference.append(item)
    payload = {
        "creator": "Albert Clownstein",
        "reviewed": catalog["reviewed"],
        "crawlers": documented + community,
        "inference": inference,
    }
    return json.dumps(payload, indent=2) + "\n"


def user_agents(catalog: dict) -> list[UserAgent]:
    agents = []
    for item in catalog["inbound"]["user_agents"]:
        patterns = tuple(item.get("header_patterns", []))
        agents.append(UserAgent(
            item["token"], item["operator"], item["purpose"], item["kind"], bool(item["header"]), item["feed"], patterns,
        ))
    return agents


def header_match_patterns(agent: UserAgent) -> tuple[str, ...]:
    if not agent.header:
        return ()
    return agent.header_patterns or (agent.token,)


def header_tokens(catalog: dict) -> list[str]:
    seen: set[str] = set()
    patterns = []
    for agent in user_agents(catalog):
        for pattern in header_match_patterns(agent):
            key = pattern.lower()
            if key in seen:
                continue
            seen.add(key)
            patterns.append(pattern)
    return patterns


def robots(tokens: list[str], note: str) -> str:
    out = [f"# {HEADER}", f"# {note}", "# robots.txt is advisory. Enforce with the WAF, nginx, or address-feed rules in this repository."]
    out.extend(f"User-agent: {token}" for token in tokens)
    out.append("Disallow: /")
    return lines(out)


def unique_ordered(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result = []
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


def robots_files(catalog: dict) -> dict[str, str]:
    agents = user_agents(catalog)
    recommended = [agent.token for agent in agents]
    training = [agent.token for agent in agents if agent.purpose == "training"]
    community = catalog["inbound"]["community_robots_tokens"]["tokens"]
    full = unique_ordered(recommended + community)
    return {
        "rules/robots-txt/robots.txt": robots(recommended, "Operator-documented and widely observed AI crawler, search, and agent tokens."),
        "rules/robots-txt/robots-training-only.txt": robots(training, "Model-training crawlers only. AI search and user-triggered fetchers remain allowed."),
        "rules/robots-txt/robots-full.txt": robots(
            full, f"Recommended tokens plus the ai.robots.txt community list retrieved {catalog['inbound']['community_robots_tokens']['retrieved']}."
        ),
    }


def nginx_http(catalog: dict, aggregate_v4: list, aggregate_v6: list) -> str:
    alternation = "|".join(rx_escape(token) for token in header_tokens(catalog))
    out = [
        f"# {HEADER}",
        "# Include inside the nginx http {} block. Pair with ai-crawlers-server.conf inside each server {} block.",
        "# If nginx sits behind a CDN or load balancer, configure ngx_http_realip_module so $remote_addr is the client.",
        "",
        "map $http_user_agent $ai_crawler_user_agent {",
        "    default 0;",
        f'    "~*(?:{alternation})" 1;',
        "}",
        "",
        "geo $ai_crawler_address {",
        "    default 0;",
    ]
    out.extend(f"    {net} 1;" for net in aggregate_v4)
    out.extend(f"    {net} 1;" for net in aggregate_v6)
    out.extend([
        "}",
        "",
        "map \"$ai_crawler_user_agent$ai_crawler_address:$uri\" $ai_crawler_block {",
        "    default 1;",
        '    "~^00:" 0;',
        '    "~:/robots\\.txt$" 0;',
        "}",
    ])
    return lines(out)


NGINX_SERVER = f"""# {HEADER}
# Include inside each nginx server {{}} block after ai-crawlers-http.conf is loaded in the http {{}} block.
# Requests from AI crawler user agents or published crawler addresses receive 403, except /robots.txt.
if ($ai_crawler_block) {{
    return 403;
}}
"""


def cloudflare_expressions(catalog: dict) -> list[str]:
    clauses = [f'(lower(http.user_agent) contains "{token.lower()}")' for token in header_tokens(catalog)]
    parts: list[list[str]] = []
    current: list[str] = []
    for clause in clauses:
        candidate = "\nor ".join(current + [clause])
        if current and len(candidate) + 1 > CLOUDFLARE_EXPRESSION_LIMIT:
            parts.append(current)
            current = [clause]
        else:
            current.append(clause)
    if current:
        parts.append(current)
    expressions = []
    for part in parts:
        expression = "\nor ".join(part)
        if len(expression) + 1 > CLOUDFLARE_EXPRESSION_LIMIT:
            raise CatalogError(f"Cloudflare expression is {len(expression)} characters; limit is {CLOUDFLARE_EXPRESSION_LIMIT}")
        expressions.append(expression + "\n")
    return expressions or ["\n"]


def aws_waf_regex_pattern_sets(catalog: dict) -> list[str]:
    pieces = [rx_escape(token.lower()) for token in header_tokens(catalog)]
    sets: list[list[str]] = [[]]
    current = ""
    for piece in pieces:
        if len(piece) > AWS_WAF_REGEX_MAX_LENGTH:
            raise CatalogError(f"AWS WAF regex piece exceeds {AWS_WAF_REGEX_MAX_LENGTH} characters")
        candidate = piece if not current else current + "|" + piece
        if current and len(candidate) > AWS_WAF_REGEX_MAX_LENGTH:
            if len(sets[-1]) >= AWS_WAF_REGEX_PER_SET:
                sets.append([])
            sets[-1].append(current)
            current = piece
        else:
            current = candidate
    if current:
        if len(sets[-1]) >= AWS_WAF_REGEX_PER_SET:
            sets.append([])
        sets[-1].append(current)
    return [lines(part) for part in sets if part] or ["\n"]


# --------------------------------------------------------------------------- #
# Assemble every output
# --------------------------------------------------------------------------- #


def build_outputs(root: Path = ROOT) -> dict[str, str]:
    catalog = load_catalog(root)
    outputs: dict[str, str] = {}

    for profile in PROFILES:
        dests = destinations(catalog, profile)
        suffix = profile_suffix(profile)
        outputs[f"rules/palo-alto/ai-inference-url-edl{suffix}.txt"] = palo_alto_url_edl(catalog, dests)
        outputs[f"rules/zscaler/ai-inference-urls{suffix}.txt"] = zscaler_urls(catalog, dests)
        outputs[f"rules/netskope/ai-inference-urls{suffix}.txt"] = netskope_urls(catalog, dests, profile)
        gateway_csv = cloudflare_gateway_csv(catalog, dests)
        if len(gateway_csv.splitlines()) - 1 > CLOUDFLARE_GATEWAY_STANDARD_LIMIT:
            print(f"warning: Cloudflare Gateway {profile} list exceeds the Standard plan limit of 1,000 entries", file=sys.stderr)
        outputs[f"rules/cloudflare-gateway/ai-inference-domains{suffix}.csv"] = gateway_csv
        outputs[f"rules/cisco-umbrella/ai-inference-destinations{suffix}.txt"] = umbrella_destinations(catalog, dests)
        outputs[f"rules/squid/ai-inference-domains{suffix}.txt"] = squid_domains(catalog, dests, profile)
        outputs[f"rules/f5/ai-inference-datagroups{suffix}.tmsh"] = f5_datagroups(catalog, dests, profile)
        outputs[f"rules/bind-rpz/ai-inference{suffix}.rpz"] = rpz_zone(catalog, dests, profile)
        outputs[f"rules/pi-hole/ai-inference-adlist{suffix}.txt"] = pihole_adlist(catalog, dests, profile)
        outputs[f"rules/pi-hole/ai-inference-domains{suffix}.txt"] = pihole_domains(catalog, dests, profile)
        outputs.update(defender_files(catalog, dests, profile))
        outputs[f"rules/suricata/ai-inference{suffix}.rules"] = suricata_egress_rules(catalog, dests, profile)

    full = destinations(catalog, "full")
    outputs["rules/netskope/ai-inference-regex.txt"] = netskope_regex(full)
    outputs["rules/squid/ai-inference-domain-regex.txt"] = squid_domain_regex(full)
    outputs["rules/squid/ai-inference-url-regex.txt"] = squid_url_regex(full)
    outputs["rules/pi-hole/ai-inference-regex.txt"] = pihole_regex(full)
    outputs["rules/f5/ai-inference.irule"] = F5_IRULE
    outputs["rules/f5/ai-inference-sni-passthrough.irule"] = F5_PASSTHROUGH_IRULE
    outputs["rules/suricata/ai-crawlers.rules"] = suricata_crawler_rules(catalog)

    outputs.update(robots_files(catalog))

    feed_data = load_feed_data(root, catalog)
    for item in feed_data:
        outputs[f"rules/ip-feeds/{item.feed.feed_id}.txt"] = lines([str(net) for net in item.ipv4 + item.ipv6])
    outputs["rules/ip-feeds/anthropic-network.txt"] = provider_network_file(catalog, "anthropic_network")
    outputs["rules/ip-feeds/openai-network.txt"] = provider_network_file(catalog, "openai_network")
    outputs["rules/ip-feeds/xai-network.txt"] = provider_network_file(catalog, "xai_network")
    aggregate_v4, aggregate_v6 = aggregate_networks(feed_data)
    outputs["rules/ip-feeds/ai-crawlers-ipv4.txt"] = lines([str(net) for net in aggregate_v4])
    outputs["rules/ip-feeds/ai-crawlers-ipv6.txt"] = lines([str(net) for net in aggregate_v6])
    outputs["rules/crowdstrike/crawler-prefixes-ipv4.txt"] = lines([str(net) for net in aggregate_v4])
    outputs["rules/crowdstrike/crawler-prefixes-ipv6.txt"] = lines([str(net) for net in aggregate_v6])
    outputs["rules/palo-alto/ai-crawlers-ip-edl.txt"] = lines([str(net) for net in aggregate_v4 + aggregate_v6])
    outputs["rules/nginx/ai-crawlers-http.conf"] = nginx_http(catalog, aggregate_v4, aggregate_v6)
    outputs["rules/nginx/ai-crawlers-server.conf"] = NGINX_SERVER
    expressions = cloudflare_expressions(catalog)
    for index, expression in enumerate(expressions):
        name = "guides/cloudflare-waf/custom-rule-expression.txt" if index == 0 else f"guides/cloudflare-waf/custom-rule-expression-{index + 1}.txt"
        outputs[name] = expression
    pattern_sets = aws_waf_regex_pattern_sets(catalog)
    for index, patterns in enumerate(pattern_sets):
        name = "guides/aws-waf/user-agent-regex-patterns.txt" if index == 0 else f"guides/aws-waf/user-agent-regex-patterns-{index + 1}.txt"
        outputs[name] = patterns
    plugin_data = plugin_catalog(catalog)
    for relative in (
        "plugins/wordpress/protect-from-ai/data/catalog.json",
        "plugins/directadmin/protect_from_ai/data/catalog.json",
        "plugins/cpanel/protect_from_ai/data/catalog.json",
    ):
        outputs[relative] = plugin_data
    module = (root / "plugins" / "shared" / "ProtectFromAI.pm").read_text(encoding="utf-8").replace("\r\n", "\n")
    if not module.endswith("\n"):
        module += "\n"
    for relative in (
        "plugins/directadmin/protect_from_ai/lib/ProtectFromAI.pm",
        "plugins/cpanel/protect_from_ai/lib/ProtectFromAI.pm",
    ):
        outputs[relative] = module
    return outputs


def write_outputs(root: Path, outputs: dict[str, str]) -> None:
    for relative, content in sorted(outputs.items()):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)


def stale_outputs(root: Path, outputs: dict[str, str]) -> list[str]:
    stale = []
    for relative, content in sorted(outputs.items()):
        path = root / relative
        if not path.is_file() or path.read_bytes().decode("utf-8") != content:
            stale.append(relative)
    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root (default: this checkout)")
    parser.add_argument("--check", action="store_true", help="exit 1 if any generated file is missing or out of date")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        outputs = build_outputs(root)
    except (CatalogError, OSError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    if args.check:
        stale = stale_outputs(root, outputs)
        for relative in stale:
            print(f"out of date: {relative}", file=sys.stderr)
        if stale:
            print("run: python tools/generate.py", file=sys.stderr)
            return 1
        print(f"{len(outputs)} generated files are current")
        return 0
    write_outputs(root, outputs)
    print(f"wrote {len(outputs)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
